version: '3'
services:
  binhex-qbittorrentvpn:
    container_name: binhex-qbittorrentvpn
    networks:
      ipvlan1:
        ipv4_address: [IP ADDRESS]
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - HOST_CONTAINERNAME=binhex-qbittorrentvpn
      - TCP_PORT_6881=6881
      - UDP_PORT_6881=6881
      - TCP_PORT_8080=8080
      - TCP_PORT_8118=8118
      - VPN_ENABLED=yes
      - VPN_USER=[VPN Service USERNAME]
      - VPN_PASS=[VPN Service Password]
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - VPN_OPTIONS=
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
      - WEBUI_PORT=8080
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - VPN_INPUT_PORTS=
      - VPN_OUTPUT_PORTS=
      - DEBUG=false
      - UMASK=000
      - PUID=99
      - PGID=100
    volumes:
      - /mnt/user/data/torrents:/downloads:rw
      - /mnt/user/appdata/binhex-qbittorrentvpn:/config:rw
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: binhex/arch-qbittorrentvpn
    
  radarr:
    container_name: radarr
    environment:
      - TZ=America/Los_Angeles
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Dicetower
      - HOST_CONTAINERNAME=radarr
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - /mnt/user/data/media/movies:/movies:rw
      - /mnt/user/data/torrents:/downloads:rw
      - /mnt/user/appdata/radarr:/config:rw
    network_mode: "service:binhex-qbittorrentvpn"
    image: lscr.io/linuxserver/radarr
    depends_on:
      - binhex-qbittorrentvpn

  sonarr:
    container_name: sonarr
    environment:
      - TZ=America/Los_Angeles
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Dicetower
      - HOST_CONTAINERNAME=sonarr
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - /mnt/user/data/media/series:/tv:rw
      - /mnt/user/data/torrents:/downloads:rw
      - /mnt/user/appdata/sonarr:/config:rw
    network_mode: "service:binhex-qbittorrentvpn"
    depends_on:
      - binhex-qbittorrentvpn
    image: lscr.io/linuxserver/sonarr
  prowlarr:
    container_name: prowlarr
    environment:
      - TZ=America/Los_Angeles
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Dicetower
      - HOST_CONTAINERNAME=prowlarr
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - /mnt/user/appdata/prowlarr:/config:rw
    network_mode: "service:binhex-qbittorrentvpn"
    depends_on:
      - binhex-qbittorrentvpn
    image: lscr.io/linuxserver/prowlarr

networks:
  ipvlan1:
    external: true
